### ISSUE TITLE
DictionaryTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-fokosun/Checkpoint1#12]
There are so many inconsistencies in your spacing in this file.

Remove the space on line 17

Remove the space on line 22

**Comment by unicodeveloper** [comment]
```php
 /**
     *#expectedException WordNotFoundException
    */
    public function testDeleteSlangFromDictionary() {
        $this->dictionary->addSlangToDictionary('gala', 'snack', 'gala as food at the gala night');
        $this->assertTrue($this->dictionary->deleteSlangFromDictionary('gala'));
        $this->assertNotContains('gala', $this->dictionary->getData());
    }
```

The `#` before expectedException, shouldn't it be `@`

**Comment by andela-fokosun** [comment]
Thanks for pointing out the spacing and # on the expectedException. i still have an issue with that though. When i tweek the test to fail, it wont be able to find y exception class. I know it has to do with namespacing. I have gone through my code to ensure namespacing is right, kindly please check where i got it wrong.

**Comment by unicodeveloper** [comment]
```php
   public function testUpdateExistingSlang() {
        $this->dictionary->addSlangToDictionary('chop', 'to eat or pieces', 'get those chops and chop them off');
        $res = $this->dictionary->updateExistingSlang('chop', 'chinese cutlery', 'one too many chop sticks to chop');
        $this->assertTrue($res);
        $this->assertNotEquals('to eat or pieces', $this->dictionary->getData()['chop']['description']);
        $this->assertEquals('chinese cutlery', $this->dictionary->getData()['chop']['description']);
    }
    public function testFindAndRetrieveSlang() {
        $this->dictionary->addSlangToDictionary('chop', 'to eat or pieces', 'get those chops and chop them off');
        $res = $this->dictionary->findAndRetrieveSlang('chop');
        $this->assertNotEmpty($res);
        $this->assertEquals('to eat or pieces', $res['description']);
    }
```

Please dont name a variable `$res`. Give it a full appropriate name

**Comment by andela-fokosun** [comment]
Fixed

**Comment by unicodeveloper** [comment]
@andela-fokosun what error does it give for that expectation?

**Comment by andela-fokosun** [comment]
ReflectionException: Class WordNotFoundException does not exist
Failed asserting that exception of type "WordExistException" is thrown.
Failed asserting that exception of type "WordNotFoundException" is thrown.

**Comment by unicodeveloper** [comment]
Yeah becuase your namespace should have been `namespace Florence\Exceptions\WordExistException;` and `Florence\Exceptions\WordNotFoundExceptions`

**Comment by unicodeveloper** [comment]
does it work now?
