### ISSUE TITLE
Test.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-fokosun/Checkpoint1#6]
What does Test.php do? and why is it there?

**Comment by busayo** [comment]
Fix these issues ASAP and come for defense tomorrow morning

**Comment by andela-fokosun** [comment]
Hi Prosper,

Test.php was committed in error, it doesn't do anything. I have deleted it
from the repo.

Thanks for pointing that out to me.

I have a question though, what time in the morning will be okay for me to
come for the defense?


On Wed, Oct 21, 2015 at 5:31 PM, Otemuyiwa Prosper <notifications@github.com
> wrote:

> Fix these issues ASAP and come for defense tomorrow morning
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andela-fokosun/Checkpoint1/issues/6#issuecomment-149953131>
> .
>



-- 
me

**Comment by busayo** [comment]
10:30 a.m
