### ISSUE TITLE
There is a .swp file in your project

### ISSUE THREAD

**Issue by unicodeveloper** [andela-fokosun/Checkpoint1#9]
Please remove the file. It does nothing

**Comment by unicodeveloper** [comment]
You closed this issue but the file still exists online
<img width="890" alt="screen shot 2015-10-24 at 11 31 27 am" src="https://cloud.githubusercontent.com/assets/2946769/10710144/db194acc-7a42-11e5-9978-83d2efb5c1b3.png">

**Comment by unicodeveloper** [comment]
reopen the issue and delete that file first before closing it

**Comment by andela-fokosun** [comment]
Removed
